# Generated by Django 4.0.4 on 2022-07-09 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuSemana',
            fields=[
                ('nrocatalogo', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Nro catalogo')),
                ('dia', models.CharField(max_length=25, verbose_name='dia')),
                ('platofondo', models.CharField(blank=True, max_length=25, null=True, verbose_name='Plato Fondo')),
                ('Ensalada', models.CharField(blank=True, max_length=25, null=True, verbose_name='Ensalada')),
                ('Postre', models.CharField(blank=True, max_length=25, null=True, verbose_name='Postre')),
            ],
        ),
    ]
